### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by mubarak** [sinetja/netty-router#12]
HTTP/1.1 request to upgrade Websocket has some issues,  for instance `/websocket` endpoint has server handler (e.g, `WebSocketServerHandler`), once websocket upgrade happens then channel only talks in websocket prorocol (such as `PingFrame`, `CloseFrame`, `TextWebsocketFrame` etc) and `HttpRequest` message is not valid anymore but
 `DualAbstractHandler extends SimpleChannelInboundHandler<HttpRequest>`. When websocket client sends `TextWebsocketFrame` as message then `SimpleChannelInboundHandler` can't accept the `TextWebsocketFrame` message and skip the handler for `TextWebsocketFrame` message (e.g, `WebSocketServerHandler`).

<img width="1881" alt="screen shot 2015-08-28 at 11 25 53 pm" src="https://cloud.githubusercontent.com/assets/668134/9560795/83bc422a-4ddd-11e5-808b-89cc0d3f51be.png">

and netty `DefaultChannelPipeline` logs
 `i.n.channel.DefaultChannelPipeline - Discarded inbound message TextWebSocketFrame(data: AdvancedLeakAwareByteBuf(PooledUnsafeDirectByteBuf(ridx: 0, widx: 4, cap: 4))) that reached at the tail of the pipeline. Please check your pipeline configuration.`

https://github.com/netty/netty/blob/netty-4.1.0.Beta5/transport/src/main/java/io/netty/channel/DefaultChannelPipeline.java#L1154

How to use multiple message types (such as `HttpRequest` and `WebsocketFrame`) using single handler with `netty-router`?

I think workaround would be creating my own `CustomChannelInboundHandler` extends from `ChannelInboundHandlerAdapter` and i need to handle both or all the required message types and take care of buffer `release`.

**Comment by ngocdaothanh** [comment]
I've just released netty-router 2.0.0.
Please use it (as always, please see [README](https://github.com/sinetja/netty-router/blob/master/README.rst) for instructions).
You should be able to download it from Maven in a few minutes.

From this version, netty-router doesn't include any handlers.
It only focus on routing logic.

So you won't have to worry about issue like this.
